jobs:
  jenkins-shared-library-example-pipeline:
    HELM_CHART_NAME: jenkins-shared-library-example-pipeline
    HELM_RELEASE_NAME: jenkins-shared-library-example-pipeline
    IMAGE_NAME: jenkins-shared-library-example-pipeline
    build: true
    deploy: false
    artifact_upload: true
    docker_build_and_push: false
    BUILD_TYPE: maven
    sample_step: true
  jenkins-shared-library-example-pipeline-nodejs:
    HELM_CHART_NAME: jenkins-shared-library-example-pipeline-nodejs
    HELM_RELEASE_NAME: jenkins-shared-library-example-pipeline-nodejs
    IMAGE_NAME: jenkins-shared-library-example-pipeline-nodejs
    build: true
    deploy: true
    artifact_upload: true
    docker_build_and_push: true
    BUILD_TYPE: npm
    sample_step: true
