jobs:
  jenkins-shared-library-example-pipeline:
    build: true
    build_type: maven
    deploy: false
    artifact_upload: true
    docker_build_and_push: false
    sample_step: true
  jenkins-shared-library-example-pipeline-nodejs:
    build: true
    build_type: npm
    deploy: true
    artifact_upload: true
    docker_build_and_push: true
    sample_step: true
